graphql:
  packages:
    - "com.santaclose.app"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: "Xn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$"
  expiredDays: 30

kakao:
  clientId: "ab0e3d8af995fbf72d461fcaf38ef7b2"
  redirectUri: "http://localhost:8080/oauth"
